### ISSUE TITLE
Decode protobuf-encoded claim values and return them in JSONRPC responses

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbrycrd#206]
RPC commands such as `getclaimbyid` return the value of a claim. For most claims, this value is a protobuf-encoded bytestring that was created using the types in https://github.com/lbryio/types. Such values should be decoded and returned as JSON in a new `value_decoded` field.

The protobuf definitions for c++ are here: https://github.com/lbryio/types/tree/master/cpp

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by ConnorBach** [comment]
Hi! I'd like to tackle this issue. Should the new value_decoded field be returned in the UniValue claim object?

**Comment by BrannonKing** [comment]
Yes, the new values should be returned in the existing UniValue result. You can safely add fields; try not to modify the other fields already coming out.

**Comment by LucianaMarques** [comment]
Hello there,

Has any pull request been made on this issue? I'd like to give it a try!

**Comment by BrannonKing** [comment]
I have seen no PRs for this yet.

**Comment by LucianaMarques** [comment]
Ok, I think I may have a solution in mind. 

Just a question: whenever commands like getclaimid are called, there is a string that represents a value of the concerned claim. Isn't what I need to do with this number basically convert the represented number in an integer?

**Comment by BrannonKing** [comment]
This issue is somewhat more complicated than numerical conversion. The claim values are passed in as binary data (hex-encoded). The binary data is output from a protobuf serializer. You won't be able to deserialize that data without the necessary protobuf definitions. The protobuf definitions are defined in an alternate project (mentioned in the first post here). Lbrycrd does have an existing reference to protobuf, so you should be able to use that directly once the types are also referenced. At present lbrycrd has no other lbryio dependencies. 

And in thinking about it, I actually think this story would be better implemented as a python script. The script would run the current export command (like the import scripts), process that data some more using the already-existing python metadata defs, and output the results. The script could even pull the metadata definition in from the web when it runs; it wouldn't need a downloaded dependency.

**Comment by LucianaMarques** [comment]
Hi, just to inform that I'm working on this. Still trying to understand some things.

**Comment by lyoshenka** [comment]
@BrannonKing can you explain how this would work as a python script? when i call `getclaimbyid`, would `lbrycrd-cli` call the python script somehow?

**Comment by BrannonKing** [comment]
I was picturing a python script that would call lbrycrd-cli (like this script: https://github.com/lbryio/lbrycrd/blob/add_claim_import_scripts/contrib/devtools/import_claims_from_claimsintrie_output.py). It would load that data (with `json.loads`, etc.). I it would pull down the current type definitions from lbryio/types. For each item in the data it would run the metadata through the protobuf parser, specifying the right protobuf def as it went. It would modify the JSON and reoutput it.

**Comment by lyoshenka** [comment]
why is this better than doing the decoding in lbrycrd? it seems like i'd basically always want the json output instead of the protobuf-serialized bytes.

**Comment by kauffj** [comment]
@BrannonKing agreed on historical aspect of (3) but not convinced this is right long-term.

**Comment by vancam-pham** [comment]
Can you tell me where to get/how to produce claims for testing. I'm now in phase of testing my python script. I'm using -regtest to produce block. However, the blocks are currently empty.

**Comment by BrannonKing** [comment]
@vancam-pham , I apologize for never replying to your query last October. That was an oversight.

**Comment by BrannonKing** [comment]
I'm closing this as rejected. It's out of scope for the foreseeable future. It is easily done in Python3 utilizing the SDK:
```python
from lbrynet.wallet.transaction import Transaction
tx = Transaction(unhexlify(raw_tx['hex']))
if tx.outputs[0].is_claim and tx.outputs[0].claim.is_stream:
	metadata = tx.outputs[0].claim.stream
```
