### ISSUE TITLE
make depends boost invalid download url link

### ISSUE THREAD

**Issue by nnmfnwl7** [lbryio/lbrycrd#407]
Im working on some build helper scripts not only predefined rules for lbrycrd "leveldb" and also "sqlite" version.

Issue comes with predefined depends build, getting error:
```
Fetching boost_1_69_0.tar.bz2 from https://bitcoincore.org/depends-sources
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
```

to reproduce, run followed command in lbrycrd directory:
```
make -j4 -C depends boost
```

Using official https://github.com/lbryio/lbrycrd.git same issue with tag "v0.17.3.3" also "v0.17.4.6"

Using Debian based OS.

For more details about scripts please read follow link. Feel free to share your ideas and feedback.
Thank you.
https://github.com/nnmfnwl7/cc.setup.helper.debian

**Comment by BrannonKing** [comment]
I'm a little confused by this, as that bitcoincore link is not what's in the file for any of the primary branches: 
https://github.com/lbryio/lbrycrd/blob/73893d2f6bfa747ff84fad6fea8a01481336a550/depends/packages/boost.mk#L3

**Comment by BrannonKing** [comment]
It looks like you must be hitting the FALLBACK_DOWNLOAD_PATH in the depends/Makefile. I'm not sure what causes that. If you go into the depends folder (via `cd`) and run something like `make -j8 NO_QT=1`, does it use the right URL in that situation?

**Comment by emmacneil** [comment]
I was hoping to start contributing to LBRY, but this issue is preventing me from building. I guess I'll start by looking into this issue.

Running `./packaging/build_linux_64bit.sh' from the root directory or `make NO_QT=1` from the depends folder both end in failure.

`Fetching boost_1_69_0.tar.bz2 from https://dl.bintray.com/boostorg/release/1.69.0/source/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden
Fetching boost_1_69_0.tar.bz2 from https://bitcoincore.org/depends-sources
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
make: *** [funcs.mk:245: /home/evan/development/lbrycrd/depends/sources/download-stamps/.stamp_fetched-boost-boost_1_69_0.tar.bz2.hash] Error 22
`

**Comment by BrannonKing** [comment]
I get 403 on the link today as well. Notice that bitcoin changed their server six months ago: https://github.com/bitcoin/bitcoin/blame/master/depends/packages/boost.mk . This should not hold you up on compilation, though. Change the link in depends/packages/boost.mk . Or use a local installation of boost. Any serious work on lbrycrd would probably be done with local dependencies rather than using "depends", perhaps in a Docker environment. 

You should coordinate any work on lbrycrd with LBRY through chat. Get in the Slack or Discord groups and discuss plans.

**Comment by emmacneil** [comment]
Changing the download path in `boost.mk` to `https://boostorg.jfrog.io/artifactory/main/release/1.69.0/source/` does allow the build script to continue to completion. Not sure if that solves the original issue since nnmfnwl7 didn't report a 403 error, but I don't think it's a coincidence.

**Comment by mjovanc** [comment]
> Changing the download path in `boost.mk` to `https://boostorg.jfrog.io/artifactory/main/release/1.69.0/source/` does allow the build script to continue to completion. Not sure if that solves the original issue since nnmfnwl7 didn't report a 403 error, but I don't think it's a coincidence.

I faced the same issue with building with Docker so I changed the download path in `boost.mk `to the link above you wrote and it seems to work now. I also see on Travis that the latest on master gives the same output as I get (see output below): [https://travis-ci.org/github/lbryio/lbrycrd/jobs/769376859](https://travis-ci.org/github/lbryio/lbrycrd/jobs/769376859)

```
Fetching boost_1_69_0.tar.bz2 from https://dl.bintray.com/boostorg/release/1.69.0/source/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden
Fetching boost_1_69_0.tar.bz2 from https://bitcoincore.org/depends-sources
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
funcs.mk:242: recipe for target '/lbrycrd/depends/sources/download-stamps/.stamp_fetched-boost-boost_1_69_0.tar.bz2.hash' failed
make: *** [/lbrycrd/depends/sources/download-stamps/.stamp_fetched-boost-boost_1_69_0.tar.bz2.hash] Error 22
```

**Comment by BrannonKing** [comment]
I'll fix this on master soon. Thanks for your patience while I've been working on my PhD the corresponding lbcd implementation.

**Comment by mjovanc** [comment]
@BrannonKing I can make a PR to fix it so you don't have to, if the link is 100% valid that is.
